from gym_exploration.envs.hardsquare_env import HardSquareEnv 
from gym_exploration.envs.variance_world import VarianceWorld 
from gym_exploration.envs.continuous_riverswim import ContinuousRiverswim 